### ISSUE TITLE
Coding while drunk: opps my bad 

### ISSUE THREAD

**Issue by grummerd** [moneroexamples/compile-monero-09-on-ubuntu-16-04#2]
These are the two alias for a ton of commands that you are appending to ~/.bashrc

```
echo "alias moneronode='rlwrap -f ~/.bitmonero/monerocommands_simplewallet.txt /opt/bitmonero/bitmonerod'" >> ~/.bashrc

echo "alias monerowallet='rlwrap -f ~/.bitmonero/monerocommands_bitmonerod.txt /opt/bitmonero/simplewallet'" >> ~/.bashrc
```

Mixed up the bitmonerod.txt file with the simplewallet.txt file

Here is the fix you can just copy and paste it in

```
echo "alias moneronode='rlwrap -f ~/.bitmonero/monerocommands_bitmonerod.txt /opt/bitmonero/bitmonerod'" >> ~/.bashrc

echo "alias monerowallet='rlwrap -f ~/.bitmonero/monerocommands_simplewallet.txt /opt/bitmonero/simplewallet'" >> ~/.bashrc
```

Sorry if this is the coding equivalent of being a grammar troll. Everyone whose anyone would catch the mistake. Maybe it's just a fun joke and i'm being too serious

**Comment by moneroexamples** [comment]
Thanks much!. Will correct it now.
