### ISSUE TITLE
Add run as a service section

### ISSUE THREAD

**Issue by grummerd** [moneroexamples/compile-monero-09-on-ubuntu-16-04#3]
This knowledge should not be forgotten. Can we include a section on [running Ubuntu as a service](https://github.com/monero-project/bitmonero/issues/977) aka  upon startup, start background daemon. There is one gotcha which ubuntu users need to know about

**Comment by moneroexamples** [comment]
Ok. I will check it, and add it. Thanks.

**Comment by moneroexamples** [comment]
@grummerd

Hi, do you have more info on this. I checked the link you provided. It references this:

https://aur.archlinux.org/cgit/aur.git/tree/bitmonerod.service?h=bitmonero-git

But the link is dead now.

Sorry it took a while to get back to this topic.

**Comment by grummerd** [comment]
Google to the rescue

All the files
https://aur.archlinux.org/cgit/aur.git/tree/?h=bitmonero-git

The file in question
https://aur.archlinux.org/cgit/aur.git/tree/monerod.service?h=bitmonero-git

Project link
https://aur.archlinux.org/packages/bitmonero-git/
